export { default as DarkModeSwitcher } from './dark-mode-switcher/dark-mode-switcher.vue'
export { default as Typography } from './typography/typography.vue'
export { default as ErrorTemplate } from './error-template/error-template.vue'
export { default as App } from './app/app.vue'
export { default as Navigation } from './navigation/navigation.vue'
